### ISSUE TITLE
Doesn't decrypt any of the useful files

### ISSUE THREAD

**Issue by dolkensp** [aftokinito/scleaksp4kbuster#4]
Also doesn't read any of the data from dataforge.

F- for (lack of) skill

**Comment by Heavybob** [comment]
Are you from another planet?

**Comment by dolkensp** [comment]
No - there's just a big chunk of data that you're not extracting with this tool

Take this for example: https://github.com/aftokinito/scleaksp4kbuster/blob/c2efb6a579372095b1156574ecdc35bcaf528811/SCLeaksP4KBuster/Program.cs#L170

The "alluran/dino"s unp4k tool doesn't have this problem :P
